version: '3.3'
services:
    mongodb-oc-p7:
        container_name: mongodb-oc-p7
        restart: always
        image: mongo
        ports:
            - ${MONGO_DB_PORT}:27017
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
        volumes:
            - sc-mongo-data:/data/db

    minio-storage-oc-p7:
        container_name: minio-oc-p7
        restart: always
        image: quay.io/minio/minio
        command: minio server /data
        ports:
            - ${MINIO_PORT}:9000
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

volumes:
    sc-mongo-data:
